version: '3.9'
services:

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    
  node-frontend:
    container_name: frontend
    build: ./frontend
    ports: 
        - "5173:5173"
  node-backend:
    container_name: backend
    build: ./line-oa-backend
    ports:
        - "3000:3000"
    env_file:
        - .env    
    depends_on:
      db:
        condition: service_healthy

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command: ["http", "host.docker.internal:3000"]
  #   ports:
  #     - 4040:4040
  #   environment:
  #     - NGROK_AUTHTOKEN=2sveDX0rDEUkNzxkbsUCz32yYdX_4LEFGYFBKHun4hWt9szKj
  #   depends_on:
  #     - node-backend
            
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:

